# Generated by Django 4.1.2 on 2022-10-11 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piano_app', '0004_lesson_alter_quiz_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='my_lesson', to='piano_app.user'),
            preserve_default=False,
        ),
    ]
